### PR TITLE
adding `common` property decorator to switch options and use it to disable better example and options

### PR DESCRIPTION
**Pull request by Huan9**
screen shot 2017-12-14 at 3 11 11 pm

### CODE REVIEW

**Comment by christav** [comment]
I'd like to see a separation in the options list between the command specific and the common options, so ti looks something like:
```
Options:
  -b|--branch <arg>   Branch name for status check
  -a|--app <arg>        Specify app

Common Options (works on all commands):
     --disable-telemetry   
  -v|--version                   Display appcenter version
```
etc.

**Comment by Huan9** [comment]
The new after and before base on the suggestion

screen shot 2017-12-15 at 12 08 12 pm

**Comment by christav** [comment]
Code looks good! @amchew does this new output look good to you?

**Comment by amchew** [comment]
@Huan9 @christav , yes this looks good to me. Thanks for the quick work Huan and Chris 👍 !

**Pull request merged**
