### PR TITLE
Version to 2.3.5

### PR DESCRIPTION
**Pull request by anywherepilot**
Bump patch version for release of dependency updates

### CODE REVIEW

**Comment by anywherepilot** [comment]
Well, great. Turns out nock, mkdirp, unzipper, mocha, tslint AND gulp use minimist and we'll have to update them all.. Doing this release without updating them is pointless, because the only other thing this release does is update the rest of the dependencies not on that list.

**Comment by anywherepilot** [comment]
I'm confused this came up now, rather than with the previous PR. Anyway, postponing till next week.

**Comment by Richienb** [comment]
@anywherepilot Many people are reporting deprecation messages from `request`. Can we replace it with `got` at some point?

**Comment by anywherepilot** [comment]
Hi @Richienb . It's the first I've heard of it. Could you open an issue so we can track it effectively? I was currently just working on upgrading dependencies, not replacing them. If something is deprecated then it should be replaced of course.

**Pull request merged**
