### PR TITLE
Print version info command in help output

### PR DESCRIPTION
**Pull request by KevinTCoughlin**
👋

Attempts to address #297 by printing version command similar to azure-cli:

```shell
$ node .\dist\index.js -h

Visual Studio App Center helps you build, test, distribute, and monitor mobile apps.

For version info, use 'appcenter --version'

Usage: appcenter <command>

Commands:
    analytics                      View events, audience info, sessions, and other anayltics for apps
    apps                           View and manage apps
    build                          Start builds, get their status, and download artifacts
    codepush                       View and manage CodePush deployments and releases
    crashes                        Upload symbols for better crash reports
    distribute                     Send builds to testers and manage distribution groups
    orgs                           Manage organizations
    profile                        Manage your profile
    telemetry                      Manage telemetry preferences
    test                           Start test runs and get their status
    tokens                         Manage API tokens
    help                           Get help using appcenter commands
    login                          Log in
    logout                         Log out
    setup-autocomplete             Setup tab completion for your shell
```

Thoughts? Admittedly is a bit odd to me printing before `Usage`.

### CODE REVIEW

**Comment by christav** [comment]
This is an interesting one, actually. I'm actually thinking of fixing this by adding a "global switches" section to the bottom of all the help pages which will include --version, --output, --debug, etc. That way we can manage the list automatically rather than having to manually edit the help.

Thoughts?

**Comment by christav** [comment]
Another thought - we can just print the version number itself as part of the help message.

**Comment by KevinTCoughlin** [comment]
👋 @christav I think both are great additions and would satisfy the initial issue :). I've seen both quite a bit in the wild myself.

**Comment by christav** [comment]
We just print the version directly in the help now, so no need for this change.

**Pull request closed without merging**
