### PR TITLE
feat: Use the original "sourcemap" and "sourcemap.hbc.map" to generate a real sourcemap

### PR DESCRIPTION
**Pull request by ryanypm**
When react-native executes the`bundle` command, if `--sourcemap-output` is selected, `index.android.bundle.packager.map` and `index.android.bundle.compiler.map` are used to generate true `index.android.bundle.map`

But `appcenter-cli` didn't do it, and `index.android.bundle.hbc.map` will also be included in the push.

[https://github.com/facebook/react-native/blob/master/react.gradle#L211](https://github.com/facebook/react-native/blob/master/react.gradle#L211)

### CODE REVIEW

**Comment by riso** [comment]
I don't have access to the pipeline, but I think it might be failing because of eslint errors. I get the following errors when running `yarn build` from my machine:

```
  402:5   error  Expected { after 'if' condition                                                                                                                                                               curly
  406:23  error  Replace `'react-native·compose-source-maps.js·scripts·is·not·found'` with `"react-native·compose-source-maps.js·scripts·is·not·found"`                                                        prettier/prettier
  411:23  error  Replace `'sourcemap·file·is·not·found'` with `"sourcemap·file·is·not·found"`                                                                                                                  prettier/prettier
  415:38  error  Replace `⏎········sourcemapOutput,⏎········jsCompilerSourceMapFile,⏎········"-o",⏎········sourcemapOutput,⏎······` with `sourcemapOutput,·jsCompilerSourceMapFile,·"-o",·sourcemapOutput`     prettier/prettier
  432:9   error  Delete `··`                                                                                                                                                                                   prettier/prettier
  437:18  error  Replace `⏎··············new·Error(`"compose-source-maps"·command·exited·with·code·${exitCode}.`)⏎··········` with `new·Error(`"compose-source-maps"·command·exited·with·code·${exitCode}.`)`  prettier/prettier
  522:1   error  Delete `··`                                                                                                                                                                                   prettier/prettier
```

**Comment by ryanypm** [comment]
> 我没有访问管道的权限，但是我认为它可能会由于错误错误而失败。`yarn build`从我的机器上运行时，出现以下错误：
> 
> ```
>   402:5   error  Expected { after 'if' condition                                                                                                                                                               curly
>   406:23  error  Replace `'react-native·compose-source-maps.js·scripts·is·not·found'` with `"react-native·compose-source-maps.js·scripts·is·not·found"`                                                        prettier/prettier
>   411:23  error  Replace `'sourcemap·file·is·not·found'` with `"sourcemap·file·is·not·found"`                                                                                                                  prettier/prettier
>   415:38  error  Replace `⏎········sourcemapOutput,⏎········jsCompilerSourceMapFile,⏎········"-o",⏎········sourcemapOutput,⏎······` with `sourcemapOutput,·jsCompilerSourceMapFile,·"-o",·sourcemapOutput`     prettier/prettier
>   432:9   error  Delete `··`                                                                                                                                                                                   prettier/prettier
>   437:18  error  Replace `⏎··············new·Error(`"compose-source-maps"·command·exited·with·code·${exitCode}.`)⏎··········` with `new·Error(`"compose-source-maps"·command·exited·with·code·${exitCode}.`)`  prettier/prettier
>   522:1   error  Delete `··`                                                                                                                                                                                   prettier/prettier
> ```

Thank you for reminding,I don’t know why my eslint was not detected successfully. I deleted node_modules and reinstalled and detected an error.

**Comment by ryanypm** [comment]
> / azp运行

fix

**Comment by n-kurdiukov-akvelon** [comment]
Hello! I've started to review the PR. Tried to merge it with latest master changes and had the Error with my usual configuration.
sourcemap error
Please could you check if you have the same error in the latest version and add some unit tests for your PR into `\test\commands\codepush\release-react-test.ts`

**Comment by russelarms** [comment]
> Hello! I've started to review the PR. Tried to merge it with latest master changes and had the Error with my usual configuration.
> 
> sourcemap error
> 
> Please could you check if you have the same error in the latest version and add some unit tests for your PR into `\test\commands\codepush\release-react-test.ts`

cc @ryanypm

**Pull request closed without merging**
