### PR TITLE
App Center CLI tab completion generates a `command not found` error

### PR DESCRIPTION
**Pull request by AndreyMitsyk**
**Problem:** App Center CLI tab completion generates a `command not found` error on MacOS and some Linux environments in `Bash`. In `zsh` and `fish` everything looks good.

**Issues:** https://github.com/Microsoft/appcenter-cli/issues/285 https://github.com/Microsoft/appcenter-cli/issues/340

**Root-cause:**
App Center CLI tab completion depends on `bash_completion` which should be enabled in `bash_profile` before `appcenter completion`.

**Changes:**
- Implemented logic to enable bash_completion in bash_profile before appcenter completion. 
- Implemented test to verify autocomplete initialization.

### CODE REVIEW

**Comment by AndreyMitsyk** [comment]
@owenniblock current logic does not have any verifications. omlette.js which we are using to enable autocomplete, adds duplicates of appcenter autocomplete if you execute `setup-autocomplete` several times. This does not break anything. Same thing for bash_completion configuration.
It should be possible to add verification if you want.
I used similar logic as we have inside https://github.com/f/omelette/blob/master/src/omelette.js so we can track failures only for our `Fs.appendFileSync`.

**Comment by AndreyMitsyk** [comment]
@owenniblock please review last iteration:
- Added logic to prevent autocomplete duplicates.
- Added exception handling.
- Added new test.

**Comment by amchew** [comment]
@AndreyMitsyk @owenniblock It is awesome that we are fixing this often requested bug. Thank you for this! 💯

**Comment by AndreyMitsyk** [comment]
@amchew could you please provide your bash profile?

**Comment by minhnguyenwp** [comment]
```
$ npm install -g appcenter-cli@2.1.1
/Users/mh/.npm-global/bin/appcenter -> /Users/mh/.npm-global/lib/node_modules/appcenter-cli/bin/appcenter.js

> fast-xml-parser@3.12.20 postinstall /Users/mh/.npm-global/lib/node_modules/appcenter-cli/node_modules/fast-xml-parser
> node tasks/postinstall.js || exit 0

Love fast-xml-parser? Check https://amitkumargupta.work for more projects and contribution.

npm WARN webpack-cli@3.3.7 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.

+ appcenter-cli@2.1.1
added 61 packages from 80 contributors, removed 40 packages, updated 43 packages and moved 5 packages in 16.644s
MacPro17:~$ appcenter -v
-bash: appcenter: command not found
MacPro17:~$ node -v
v10.15.3
MacPro17:~$ npm -v
6.4.1

```

Hi, i have same issue, i have no idea to solve. can any one help me?

**Comment by owenniblock** [comment]
Hi @minhnguyenwp - I don't believe that this is the same issue (you're not getting the error on tab completion here?)

Please could you raise this as a new Issue so someone can take a look?

**Pull request merged**
