### PR TITLE
[CodePush] release-react: add param to specify path to project.pbxproj file

### PR DESCRIPTION
**Pull request by giangdhwhtbr**
**Issue**: In multi workspaces code structure, if the app is in a child folder and all dependencies is declared from root folder. I will need to run the command from root folder. In this case the file project.pbxproj will not be found in these paths: "ios/my-app.xcodeproj/project.pbxproj", "ios/project.pbxproj"
**Ref**: #851 
**Solution**: Add a param to let user to manually specify path to to project.pbxproj file

### CODE REVIEW

**Comment by pbernasconi** [comment]
Can we get this merged? This is a great fix for a local problem I have too with yarn workspaces

**Comment by DmitriyKirakosyan** [comment]
Hi @pbernasconi, thank you for bumping this thread. We're currently testing the changes and will merge once we verify that it works as expected.

**Comment by DmitriyKirakosyan** [comment]
I opened a new PR based on this one. Added a couple of tweaks to improve the UX: https://github.com/microsoft/appcenter-cli/pull/1497.
Please track the progress in the new PR.
Closing this one.

**Pull request closed without merging**
