### PR TITLE
Updates the UITest template zip location to point to 1.1

### PR DESCRIPTION
**Pull request by owenniblock**
Updates generate command to use new templates.

### CODE REVIEW

**Comment by christav** [comment]
@krukow Thanks, I'll merge and release tomorrow - well, later today :-) - morning.

**Comment by owenniblock** [comment]
I've confirmed that `ts-node src/index.ts test generate uitest --platform android --output-path ~/tmp-gen` pulls down the latest .zip - I'm also not entirely sure how this is used by the launch test. Should we find that out before this goes live?

**Comment by krukow** [comment]
Yes, this goes through the normal QA process

**Comment by owenniblock** [comment]
Don't merge this yet :) Explanation below.

**Comment by owenniblock** [comment]
Talking to Tomasz I've now got a better understanding of the build process behind the launch test.

There is a reference to the project name in one of the build TS files. I will detail this on the VSTS ticket but the upshot is that before we release this to the CLI we need to:
1. Update this reference in the script.
2. Do some magic to migrate users who already have this script.

We'll have to get all this in place before we release this change to the cli because the script currently takes the _latest_ version of the appcenter-cli.

I would suggest we patch Android-1.0.zip and iOS-1.0.zip with the latest UITest to fix the broken package and then plan this out given the new knowledge.

**Comment by krukow** [comment]
@owenniblock thanks for the update

**Comment by krukow** [comment]
@owenniblock @christav publishing this is safe - please merge and publish

**Comment by owenniblock** [comment]
Ok, I've confirmed with the build team this won't affect customers. So we're good to go with the original plan - sorry for the delay but I wanted to be cautious after talking to Tomasz :)

**Pull request merged**
